import { useMemo, useState } from "react";
import { motion } from "motion/react";
import { Filter, Search, X } from "lucide-react";
import type { TemplateOut } from "../types/api";
import { EmptyState } from "./EmptyState";
import { TemplateCard } from "./TemplateCard";

interface TemplateBrowserProps {
  templates: TemplateOut[];
  onRunPipeline: () => void;
}

export function TemplateBrowser({ templates, onRunPipeline }: TemplateBrowserProps) {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("all");

  const categories = useMemo(
    () =>
      Array.from(new Set(templates.map((template) => template.category).filter(Boolean))).sort() as string[],
    [templates],
  );

  const filteredTemplates = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    return templates.filter((template) => {
      if (category !== "all" && template.category !== category) return false;
      if (!normalizedQuery) return true;
      const haystack = [
        template.subject_template,
        template.body_template,
        template.category,
        template.tone,
        template.intent,
        template.sentiment,
      ]
        .join(" ")
        .toLowerCase();
      return haystack.includes(normalizedQuery);
    });
  }, [category, query, templates]);

  const filtersActive = query.trim().length > 0 || category !== "all";

  return (
    <section className="section-shell" id="templates">
      <div className="section-heading flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="section-kicker">Templates</p>
          <h2>Template browser</h2>
          <p>Explore reusable templates generated by the backend from clustered email patterns.</p>
        </div>
        {templates.length ? (
          <span className="badge whitespace-nowrap">
            {filteredTemplates.length} of {templates.length} shown
          </span>
        ) : null}
      </div>

      {!templates.length ? (
        <EmptyState
          title="No templates generated yet"
          description="Run the pipeline to generate a browsable set of professional email templates from your dataset."
          action={
            <button type="button" onClick={onRunPipeline} className="premium-button">
              Run pipeline
            </button>
          }
        />
      ) : (
        <>
          <motion.div
            className="glass-card mb-6 grid gap-3 p-4 md:grid-cols-[1fr_220px_auto]"
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-60px" }}
            transition={{ duration: 0.4 }}
          >
            <label className="relative block">
              <span className="sr-only">Search templates</span>
              <Search
                className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500"
                aria-hidden="true"
              />
              <input
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                className="input-shell w-full pl-11 pr-10"
                placeholder="Search subject, body, tone, intent..."
              />
              {query ? (
                <button
                  type="button"
                  onClick={() => setQuery("")}
                  className="absolute right-3 top-1/2 -translate-y-1/2 rounded-full p-1 text-slate-500 transition hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300/60"
                  aria-label="Clear search"
                >
                  <X className="h-3.5 w-3.5" aria-hidden="true" />
                </button>
              ) : null}
            </label>

            <label className="relative block">
              <span className="sr-only">Filter by category</span>
              <Filter
                className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500"
                aria-hidden="true"
              />
              <select
                value={category}
                onChange={(event) => setCategory(event.target.value)}
                className="input-shell w-full appearance-none pl-11"
              >
                <option value="all">All categories</option>
                {categories.map((item) => (
                  <option key={item} value={item}>
                    {item}
                  </option>
                ))}
              </select>
            </label>

            {filtersActive ? (
              <button
                type="button"
                onClick={() => {
                  setQuery("");
                  setCategory("all");
                }}
                className="ghost-button h-full justify-self-end px-4"
              >
                <X className="h-3.5 w-3.5" aria-hidden="true" />
                Clear
              </button>
            ) : (
              <span className="hidden md:block" />
            )}
          </motion.div>

          {filteredTemplates.length ? (
            <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
              {filteredTemplates.map((template, index) => (
                <TemplateCard key={template.template_id} template={template} index={index} />
              ))}
            </div>
          ) : (
            <EmptyState
              title="No matching templates"
              description="Try a different search term or clear the category filter."
              action={
                <button
                  type="button"
                  className="secondary-button"
                  onClick={() => {
                    setQuery("");
                    setCategory("all");
                  }}
                >
                  Clear filters
                </button>
              }
            />
          )}
        </>
      )}
    </section>
  );
}
