import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import type { TemplateOut } from "../types/api";
import { EmptyState } from "./EmptyState";
import { TemplateCard } from "./TemplateCard";

interface TemplateBrowserProps {
  templates: TemplateOut[];
  onRunPipeline: () => void;
}

export function TemplateBrowser({ templates, onRunPipeline }: TemplateBrowserProps) {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("all");

  const categories = useMemo(
    () => Array.from(new Set(templates.map((template) => template.category).filter(Boolean))).sort(),
    [templates],
  );

  const filteredTemplates = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    return templates.filter((template) => {
      if (category !== "all" && template.category !== category) return false;
      if (!normalizedQuery) return true;
      const haystack = [
        template.subject_template,
        template.body_template,
        template.category,
        template.tone,
        template.intent,
        template.sentiment,
      ]
        .join(" ")
        .toLowerCase();
      return haystack.includes(normalizedQuery);
    });
  }, [category, query, templates]);

  return (
    <section className="section-shell" id="templates">
      <div className="section-heading">
        <p className="section-kicker">Templates</p>
        <h2>Template browser</h2>
        <p>
          Explore reusable templates generated by the backend from clustered email patterns.
        </p>
      </div>

      {!templates.length ? (
        <EmptyState
          title="No templates generated yet"
          description="Run the pipeline to generate a browsable set of professional email templates."
          action={
            <button type="button" onClick={onRunPipeline} className="premium-button">
              Run pipeline
            </button>
          }
        />
      ) : (
        <>
          <div className="glass-card mb-5 grid gap-3 p-4 md:grid-cols-[1fr_220px]">
            <label className="relative block">
              <Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />
              <input
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                className="input-shell w-full pl-11"
                placeholder="Search subject, body, tone, intent..."
                aria-label="Search templates"
              />
            </label>
            <select
              value={category}
              onChange={(event) => setCategory(event.target.value)}
              className="input-shell"
              aria-label="Filter by category"
            >
              <option value="all">All categories</option>
              {categories.map((item) => (
                <option key={item} value={item ?? ""}>
                  {item}
                </option>
              ))}
            </select>
          </div>

          {filteredTemplates.length ? (
            <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
              {filteredTemplates.map((template, index) => (
                <TemplateCard key={template.template_id} template={template} index={index} />
              ))}
            </div>
          ) : (
            <EmptyState
              title="No matching templates"
              description="Try a different search term or clear the category filter."
            />
          )}
        </>
      )}
    </section>
  );
}
